from django.urls import path
from .views import (
    article_detail,
    articles_list,
    auth_login,
    auth_logout,
    auth_register,
    auth_user,
    calendar_list,
    categories_list,
    club_detail,
    club_join,
    club_leave,
    clubs_list,
    diary_entries,
    dialogs_list,
    exchange_confirm,
    exchange_detail,
    exchange_reviews,
    exchanges_list,
    forum_notification_read,
    forum_notifications,
    listing_detail,
    listings,
    map_points,
    messages_with_user,
    ping,
    profile_me_update,
    profile_public,
    profile_reviews,
    topic_detail,
    topic_subscribe,
    topic_post_create,
    topic_unsubscribe,
    topics_list,
    users_list,
)

urlpatterns = [
    path("ping", ping),
    path("ping/", ping), # domain.com/ping/
    path("auth/register/", auth_register), # domain.com/auth/register/
    path("auth/login/", auth_login),
    path("auth/logout/", auth_logout),
    path("auth/user/", auth_user),
    path("profiles/<int:pk>/", profile_public),
    path("profiles/<int:pk>/reviews/", profile_reviews),
    path("profiles/me/", profile_me_update),
    path("articles/", articles_list),
    path("articles/<slug:slug>/", article_detail),
    path("calendar/", calendar_list),
    path("categories/", categories_list),
    path("clubs/", clubs_list),
    path("clubs/<int:pk>/", club_detail),
    path("clubs/<int:pk>/join/", club_join),
    path("clubs/<int:pk>/leave/", club_leave),
    path("topics/", topics_list),
    path("topics/<int:pk>/", topic_detail),
    path("topics/<int:pk>/posts/", topic_post_create),
    path("topics/<int:pk>/subscribe/", topic_subscribe),
    path("topics/<int:pk>/unsubscribe/", topic_unsubscribe),
    path("forum/notifications/", forum_notifications),
    path("forum/notifications/<int:pk>/read/", forum_notification_read),
    path("listings/", listings),
    path("listings/<int:pk>/", listing_detail),
    path("exchanges/", exchanges_list),
    path("exchanges/<int:pk>/", exchange_detail),
    path("exchanges/<int:pk>/confirm/", exchange_confirm),
    path("exchanges/<int:pk>/reviews/", exchange_reviews),
    path("diary/", diary_entries),
    path("map/", map_points),
    path("users/", users_list),
    path("messages/", dialogs_list),
    path("messages/<int:user_id>/", messages_with_user),
]