name: gor-sad

services:
  backend:
    build:
      context: ./backend
    container_name: gor-sad-backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./frontend/out:/frontend/out:ro
    ports:
      - "8000:8000" # Запуск Django на порту 8000
